# Default image (https://hub.docker.com/r/microsoft/dotnet-sdk)
# Multiarch image, it has both Linux and Windows versions
image: mcr.microsoft.com/dotnet/sdk:10.0

stages:
  - build
  - test

include:
  # NuGet Dependency Scanning
  # https://docs.gitlab.com/ee/user/application_security/dependency_scanning/
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  # Secret Detection
  # https://docs.gitlab.com/user/application_security/secret_detection/
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  # Static Application Security Testing (SAST)
  # https://docs.gitlab.com/user/application_security/sast/
  - template: Jobs/SAST.gitlab-ci.yml
  # Static analysis-based Code Quality evaluation for .NET/C#
  # https://szofttech.inf.elte.hu/components/code-quality-dotnet
  - component: szofttech.inf.elte.hu/components/code-quality-dotnet/windows@2

variables:
  # Enable GitLab Advanced SAST (Ultimate feature)
  GITLAB_ADVANCED_SAST_ENABLED: true

# Build model
# (Uses Linux-based runner, because windows tag is NOT specified.)
build_model:
  stage: build
  before_script:
    - dotnet --version
  script:
    - dotnet build src/MiniTransportTycoon.Core/MiniTransportTycoon.Core.csproj
    - dotnet build src/MiniTransportTycoon.Game/MiniTransportTycoon.Game.csproj

# Build complete solution
# (Uses Windows-based runner, because windows tag IS specified.)
build_view:
  stage: build
  # Use a Windows Server Core based docker image
  # The default mcr.microsoft.com/dotnet/sdk:10.0 would depend on Windows Nano Server, 
  # which is not enough for us, as it does not containt the desktop packs.
  image: mcr.microsoft.com/dotnet/sdk:10.0-windowsservercore-ltsc2025
  tags: [windows]
  before_script:
    - dotnet --version
  script:
    - dotnet build src/MiniTransportTycoon.UI/MiniTransportTycoon.UI.csproj

# Test Stage
# (Uses Linux-based runner, because windows tag is NOT specified.)
test_model:
  stage: test
  variables:
    TEST_PROJECT: "MiniTransportTycoon.Test"
  before_script:
    - dotnet restore "$TEST_PROJECT" --packages .nuget
  script:
    - >
      dotnet test "$TEST_PROJECT" --no-restore
      --logger:"junit;LogFilePath=TestResults.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
      --collect:"XPlat Code Coverage"

    - apt-get update -yqq
    - apt-get install -yqq bc
    - dotnet tool install --tool-path . dotnet-reportgenerator-globaltool

    - ./reportgenerator "-reports:$CI_PROJECT_DIR/$TEST_PROJECT/TestResults/*/coverage.cobertura.xml" "-targetdir:report" "-reporttypes:Cobertura"
    - ./reportgenerator "-reports:$CI_PROJECT_DIR/$TEST_PROJECT/TestResults/*/coverage.cobertura.xml" "-targetdir:report/html" "-reporttypes:Html"

    - line_rate="$(grep -o 'line-rate=\"[^\"]*\"' ./report/Cobertura.xml | head -n 1 | cut -d '\"' -f2)"
    - coverage=$(echo "$line_rate * 100" | bc -l)
    - 'printf "TOTAL_COVERAGE=%2.2f\n" "$coverage"'

  artifacts:
    when: always
    paths:
      - MiniTransportTycoon.Test/TestResults.xml
      - MiniTransportTycoon.Test/TestResults/*/coverage.cobertura.xml
      - report/html/
    reports:
      junit:
        - MiniTransportTycoon.Test/TestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: MiniTransportTycoon.Test/TestResults/*/coverage.cobertura.xml

  coverage: '/TOTAL_COVERAGE=(\d+.\d+)/'
  cache:
    key: "unittest-$CI_COMMIT_REF_SLUG"
    paths:
      - .nuget