<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.Compute" Version="4.9.4" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.6" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniTransportTycoon.Game\MiniTransportTycoon.Game.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Rendering\shaders\default.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\shaders\default.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Roads\" />
  </ItemGroup>

</Project>
